[workspace]
members = [
    "common",
    "tensor",
    "causal-lm",
    "chat-template",
    "service",
    "web-api",
    "android",
    "xtask",

    "devices/common",
    "devices/common-cpu",
    "devices/nvidia-gpu",
    "devices/cambricon-mlu",
    "devices/ascend-card",

    "models/llama/common",
    "models/llama/common-cpu",
    "models/llama/nvidia-gpu",
    "models/llama/nvidia-gpu-distributed",
    "models/llama/cambricon-mlu",
    "models/mixtral/common",
    "models/mixtral/cpu",
]
resolver = "2"

[workspace.dependencies]
half = "2.4"
log = "0.4"
itertools = "0.13"
serde = "1.0"
serde_json = "1.0"
memmap2 = "0.9"
tokio = { version = "1.40", features = ["rt-multi-thread", "sync"] }
digit-layout = "0.0"
build-script-cfg = "0.0"

operators = { git = "https://github.com/YdrMaster/operators-rs", rev = "4db3c62", default-features = false }
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "d089ada" }
search-neuware-tools = "0.0"
search-ascend-tools = { git = "https://github.com/InfiniTensor/ascendcl", rev = "1e7a696" }
